In [4]:
import numpy as np
import pandas as pd

In [5]:
df = pd.read_csv('student_placement_career_success_dataset.csv')

In [6]:
df.head()

,student_id,age,gender,state,city_tier,college_tier,branch,degree,cgpa,backlog_history,...,work_mode,salary_lpa,interview_rounds_cleared,offer_count,joining_delay_months,layoffs_risk_score,AI_tool_usage_frequency,prompt_engineering_skill,AI_fear_score,adaptability_score
0,STU00001,22,Male,Karnataka,1,2,Computer Science,MCA,6.71,3,...,Remote,17.36,4,1,2,62,55,55,19,81
1,STU00002,20,Male,Tamil Nadu,2,3,AI & DS,BTech,6.14,0,...,Onsite,18.22,3,3,0,55,66,52,54,76
2,STU00003,23,Female,Uttar Pradesh,3,2,Computer Science,BTech,7.11,0,...,Remote,22.08,1,3,1,79,69,67,49,34
3,STU00004,25,Male,Maharashtra,2,3,Civil,BTech,7.41,0,...,Remote,20.87,2,1,2,44,44,65,61,46
4,STU00005,25,Female,West Bengal,3,3,Civil,BE,8.29,0,...,Onsite,20.57,5,3,5,23,57,67,71,44

In [7]:
df.shape

(25000, 44)

In [8]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 25000 entries, 0 to 24999
Data columns (total 44 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   student_id                  25000 non-null  object
 1   age                         25000 non-null  int64
 2   gender                      25000 non-null  object
 3   state                       25000 non-null  object
 4   city_tier                   25000 non-null  int64
 5   college_tier                25000 non-null  int64
 6   branch                      25000 non-null  object
 7   degree                      25000 non-null  object
 8   cgpa                        25000 non-null  float64
 9   backlog_history             25000 non-null  int64
 10  attendance_percentage       25000 non-null  float64
 11  primary_language            25000 non-null  object
 12  DSA_problems_solved         25000 non-null  int64
 13  GitHub_repos                24500 non-null  float64
 14  hackathons_participated     25000 non-null  int64
 15  development_projects_count  25000 non-null  int64
 16  AI_ML_projects              25000 non-null  int64
 17  internships_completed       25000 non-null  int64
 18  resume_score                25000 non-null  int64
 19  communication_skills        25000 non-null  int64
 20  aptitude_score              25000 non-null  int64
 21  mock_interview_score        24500 non-null  float64
 22  sleep_hours                 24500 non-null  float64
 23  screen_time                 25000 non-null  float64
 24  gaming_hours                25000 non-null  float64
 25  study_hours_daily           25000 non-null  float64
 26  stress_level                25000 non-null  int64
 27  burnout_score               25000 non-null  int64
 28  gym_frequency               25000 non-null  int64
 29  family_income_lpa           25000 non-null  float64
 30  self_learning_hours         25000 non-null  float64
 31  motivation_level            25000 non-null  int64
 32  placement_status            25000 non-null  object
 33  company_type                24596 non-null  object
 34  work_mode                   24596 non-null  object
 35  salary_lpa                  25000 non-null  float64
 36  interview_rounds_cleared    25000 non-null  int64
 37  offer_count                 25000 non-null  int64
 38  joining_delay_months        25000 non-null  int64
 39  layoffs_risk_score          25000 non-null  int64
 40  AI_tool_usage_frequency     25000 non-null  int64
 41  prompt_engineering_skill    25000 non-null  int64
 42  AI_fear_score               25000 non-null  int64
 43  adaptability_score          25000 non-null  int64
dtypes: float64(11), int64(24), object(9)
memory usage: 8.4+ MB

In [9]:
df.describe()

,age,city_tier,college_tier,cgpa,backlog_history,attendance_percentage,DSA_problems_solved,GitHub_repos,hackathons_participated,development_projects_count,...,motivation_level,salary_lpa,interview_rounds_cleared,offer_count,joining_delay_months,layoffs_risk_score,AI_tool_usage_frequency,prompt_engineering_skill,AI_fear_score,adaptability_score
count,25000.000000,25000.000000,25000.000000,25000.000000,25000.000000,25000.000000,25000.000000,24500.000000,25000.000000,25000.000000,...,25000.0000,25000.000000,25000.000000,25000.000000,25000.00000,25000.000000,25000.000000,25000.000000,25000.000000,25000.000000
mean,22.507520,2.104360,2.354160,7.460975,0.468040,77.942360,646.777800,18.688490,2.612720,6.396520,...,69.3320,19.006936,2.972560,1.967400,2.45592,34.786640,59.333080,60.375200,44.549720,64.460400
std,1.706898,0.768201,0.726217,0.846094,0.810262,9.956108,124.989386,9.219579,1.835709,2.631921,...,14.7297,4.244388,1.445811,0.845107,1.71551,15.110894,19.396358,16.647395,19.782843,14.944899
min,20.000000,1.000000,1.000000,5.000000,0.000000,45.000000,185.000000,0.000000,0.000000,1.000000,...,5.0000,0.000000,0.000000,0.000000,0.00000,0.000000,0.000000,0.000000,0.000000,1.000000
25%,21.000000,2.000000,2.000000,6.890000,0.000000,71.200000,562.000000,12.000000,1.000000,5.000000,...,59.0000,16.750000,2.000000,1.000000,1.00000,24.000000,46.000000,49.000000,31.000000,54.000000
50%,22.000000,2.000000,3.000000,7.460000,0.000000,78.000000,646.000000,18.000000,3.000000,6.000000,...,70.0000,19.130000,3.000000,2.000000,2.00000,35.000000,60.000000,60.000000,45.000000,64.000000
75%,24.000000,3.000000,3.000000,8.030000,1.000000,84.900000,731.000000,25.000000,4.000000,8.000000,...,80.0000,21.570000,4.000000,3.000000,4.00000,45.000000,73.000000,72.000000,58.000000,75.000000
max,25.000000,3.000000,3.000000,10.000000,3.000000,100.000000,1163.000000,60.000000,10.000000,18.000000,...,100.0000,35.100000,5.000000,3.000000,5.00000,100.000000,100.000000,100.000000,100.000000,100.000000

In [10]:
df.columns

Index(['student_id', 'age', 'gender', 'state', 'city_tier', 'college_tier',
       'branch', 'degree', 'cgpa', 'backlog_history', 'attendance_percentage',
       'primary_language', 'DSA_problems_solved', 'GitHub_repos',
       'hackathons_participated', 'development_projects_count',
       'AI_ML_projects', 'internships_completed', 'resume_score',
       'communication_skills', 'aptitude_score', 'mock_interview_score',
       'sleep_hours', 'screen_time', 'gaming_hours', 'study_hours_daily',
       'stress_level', 'burnout_score', 'gym_frequency', 'family_income_lpa',
       'self_learning_hours', 'motivation_level', 'placement_status',
       'company_type', 'work_mode', 'salary_lpa', 'interview_rounds_cleared',
       'offer_count', 'joining_delay_months', 'layoffs_risk_score',
       'AI_tool_usage_frequency', 'prompt_engineering_skill', 'AI_fear_score',
       'adaptability_score'],
      dtype='object')

In [11]:
print(df['mock_interview_score'].head(10))

0      NaN
1     80.0
2     81.0
3    100.0
4     68.0
5     70.0
6     72.0
7     96.0
8     77.0
9     83.0
Name: mock_interview_score, dtype: float64

In [12]:
#How many students are Placed vs Not Placed? Show the count

df['placement_status'].value_counts()

placement_status
Placed        24596
Not Placed      404
Name: count, dtype: int64

In [13]:
#Which columns have missing values? How many nulls in each?
df.isna().sum()

student_id                      0
age                             0
gender                          0
state                           0
city_tier                       0
college_tier                    0
branch                          0
degree                          0
cgpa                            0
backlog_history                 0
attendance_percentage           0
primary_language                0
DSA_problems_solved             0
GitHub_repos                  500
hackathons_participated         0
development_projects_count      0
AI_ML_projects                  0
internships_completed           0
resume_score                    0
communication_skills            0
aptitude_score                  0
mock_interview_score          500
sleep_hours                   500
screen_time                     0
gaming_hours                    0
study_hours_daily               0
stress_level                    0
burnout_score                   0
gym_frequency                   0
family_income_lpa               0
self_learning_hours             0
motivation_level                0
placement_status                0
company_type                  404
work_mode                     404
salary_lpa                      0
interview_rounds_cleared        0
offer_count                     0
joining_delay_months            0
layoffs_risk_score              0
AI_tool_usage_frequency         0
prompt_engineering_skill        0
AI_fear_score                   0
adaptability_score              0
dtype: int64

In [14]:
#What is the average CGPA of all students?
df['cgpa'].mean()

np.float64(7.4609752)

In [15]:
#List all unique branches in the dataset.
df['branch'].unique()

array(['Computer Science', 'AI & DS', 'Civil', 'Electronics',
       'Information Technology', 'Mechanical'], dtype=object)

In [16]:
#What is the average salary (salary_lpa) for each company type?

a = df.groupby('company_type')['salary_lpa'].mean()
a

company_type
MNC              19.287854
Product-Based    19.362896
Service-Based    19.340988
Startup          19.285312
Name: salary_lpa, dtype: float64

In [17]:
#Filter students who have more than 5 AI/ML projects and are Placed. How many are there?

df[(df['AI_ML_projects']>5) & (df['placement_status'] == 'Placed')]

,student_id,age,gender,state,city_tier,college_tier,branch,degree,cgpa,backlog_history,...,work_mode,salary_lpa,interview_rounds_cleared,offer_count,joining_delay_months,layoffs_risk_score,AI_tool_usage_frequency,prompt_engineering_skill,AI_fear_score,adaptability_score
8,STU00009,20,Male,Karnataka,2,3,Civil,BE,6.70,0,...,Onsite,20.70,1,3,4,46,66,100,62,72
26,STU00027,23,Female,Karnataka,3,2,AI & DS,BE,7.22,0,...,Remote,22.71,3,2,0,29,66,84,56,71
64,STU00065,23,Female,West Bengal,1,3,Civil,MCA,6.72,0,...,Remote,19.70,1,3,1,58,43,81,53,86
72,STU00073,21,Male,Delhi,1,2,Information Technology,BE,7.96,1,...,Remote,26.91,1,3,3,40,81,68,18,61
76,STU00077,22,Male,Gujarat,3,1,Computer Science,BTech,8.97,0,...,Hybrid,28.08,1,3,0,44,33,87,53,49
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
24899,STU24900,24,Female,Uttar Pradesh,3,3,Information Technology,BE,6.59,0,...,Onsite,19.59,2,1,4,22,22,68,19,70
24908,STU24909,23,Female,Maharashtra,3,1,Civil,BTech,8.27,0,...,Onsite,27.58,1,1,3,44,28,83,30,70
24953,STU24954,22,Female,Tamil Nadu,1,2,Information Technology,BTech,7.81,0,...,Onsite,20.23,5,1,1,48,69,77,34,77
24967,STU24968,20,Male,Karnataka,3,3,Civil,BTech,9.75,0,...,Onsite,29.52,1,1,1,31,46,65,35,84
24973,STU24974,23,Male,Delhi,3,2,Mechanical,BE,6.52,0,...,Hybrid,16.14,2,1,4,30,48,58,71,49

In [18]:
#Which branch has the highest placement rate (% of students placed)?
b = df.groupby('placement_status')['branch']
for i,v in b:
    if i == 'Placed':
        placed = v.value_counts()
        print(placed)

branch
Mechanical                4186
Computer Science          4140
AI & DS                   4107
Information Technology    4101
Civil                     4091
Electronics               3971
Name: count, dtype: int64

In [19]:
#placed = df[df['placement_status'] == 'Placed'].groupby('branch')['student_id'].count()
#print(placed)

In [20]:
total = df.groupby('branch')['student_id'].count()
print(total)

branch
AI & DS                   4182
Civil                     4151
Computer Science          4203
Electronics               4053
Information Technology    4166
Mechanical                4245
Name: student_id, dtype: int64

In [21]:
rate = (placed / total) * 100
print(rate)

branch
AI & DS                   98.206600
Civil                     98.554565
Computer Science          98.501071
Electronics               97.976807
Information Technology    98.439750
Mechanical                98.610130
dtype: float64

In [22]:
rate.sort_values(ascending=False)
print(rate.idxmax())

Mechanical

In [23]:
print(df['mock_interview_score'].isnull().sum())
print(df['GitHub_repos'].isnull().sum())

500
500

In [24]:
#Fill missing values in GitHub_repos and mock_interview_score with their median. Confirm no nulls remain.

df['GitHub_repos'] = df['GitHub_repos'].fillna(df['GitHub_repos'].median())
#df['mock_interview_score'] = pd.to_numeric(df['mock_interview_score'],errors='coerce')
df['mock_interview_score'] = df['mock_interview_score'].fillna(df['mock_interview_score'].median())

In [25]:
print(df['mock_interview_score'].isnull().sum())
print(df['GitHub_repos'].isnull().sum())

0
0

In [26]:
#Find the 25th, 50th, and 75th percentile of salary_lpa using NumPy.
np.percentile(df['salary_lpa'].dropna(),[25,50,75])

array([16.75, 19.13, 21.57])

In [27]:
#Create a new column high_cgpa: 1 if cgpa > 8, else 0. Use np.where()
df [ 'high_cgpa'] = np.where(df['cgpa'] > 8,1,0)

In [28]:
df

,student_id,age,gender,state,city_tier,college_tier,branch,degree,cgpa,backlog_history,...,salary_lpa,interview_rounds_cleared,offer_count,joining_delay_months,layoffs_risk_score,AI_tool_usage_frequency,prompt_engineering_skill,AI_fear_score,adaptability_score,high_cgpa
0,STU00001,22,Male,Karnataka,1,2,Computer Science,MCA,6.71,3,...,17.36,4,1,2,62,55,55,19,81,0
1,STU00002,20,Male,Tamil Nadu,2,3,AI & DS,BTech,6.14,0,...,18.22,3,3,0,55,66,52,54,76,0
2,STU00003,23,Female,Uttar Pradesh,3,2,Computer Science,BTech,7.11,0,...,22.08,1,3,1,79,69,67,49,34,0
3,STU00004,25,Male,Maharashtra,2,3,Civil,BTech,7.41,0,...,20.87,2,1,2,44,44,65,61,46,0
4,STU00005,25,Female,West Bengal,3,3,Civil,BE,8.29,0,...,20.57,5,3,5,23,57,67,71,44,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
24995,STU24996,23,Female,Telangana,2,1,Computer Science,MCA,8.42,0,...,26.74,2,2,3,26,55,53,26,53,1
24996,STU24997,20,Female,Tamil Nadu,2,2,Civil,BTech,7.45,1,...,16.07,1,3,2,27,44,53,81,47,0
24997,STU24998,24,Male,Karnataka,2,3,Mechanical,MCA,7.34,0,...,20.22,4,1,4,17,43,72,24,87,0
24998,STU24999,20,Male,Delhi,2,2,Information Technology,BTech,7.59,1,...,19.79,2,2,3,49,93,53,59,77,0
24999,STU25000,23,Female,Maharashtra,1,2,Civil,BTech,7.67,0,...,16.84,4,1,4,27,81,57,63,55,0

In [29]:
df['high_cgpa'].head(20)

0     0
1     0
2     0
3     0
4     1
5     0
6     0
7     0
8     0
9     0
10    0
11    0
12    1
13    0
14    1
15    0
16    0
17    0
18    1
19    1
Name: high_cgpa, dtype: int64

In [30]:
#Compare average prompt_engineering_skill between Placed and Not Placed students.
df['prompt_engineering_skill'].groupby(df['placement_status']).mean()

placement_status
Not Placed    56.014851
Placed        60.446821
Name: prompt_engineering_skill, dtype: float64

In [31]:
#Find which 3 numeric columns have the strongest correlation with salary_lpa.

df.corr(numeric_only=True)['salary_lpa'].sort_values(ascending=False).head(4)

salary_lpa                    1.000000
internships_completed         0.541650
development_projects_count    0.507059
cgpa                          0.494012
Name: salary_lpa, dtype: float64

In [32]:
#Filter students with AI_ML_projects > 2 AND Placed — what's their average salary?

result = df[(df['AI_ML_projects']>2) & (df['placement_status'] == 'Placed')] 
print(result['salary_lpa'].mean())

20.618443109218134

In [33]:
#Make a pivot table: average salary by branch and work_mode.
pd.pivot_table(df,
              values='salary_lpa',
              index='branch',
              columns='work_mode',
              aggfunc='mean')

work_mode                  Hybrid     Onsite     Remote
branch
AI & DS                 19.226337  19.234127  19.281594
Civil                   19.489316  19.383361  19.245660
Computer Science        19.261308  19.287193  19.303727
Electronics             19.343064  19.280933  19.358818
Information Technology  19.330198  19.213897  19.419282
Mechanical              19.343879  19.308190  19.424401

In [34]:
 #Among placed students from Tier 1 colleges, what is the average AI_tool_usage_frequency vs Tier 2 and Tier 3?
placed = df[df['placement_status'] == 'Placed']
placed.groupby('college_tier')['AI_tool_usage_frequency'].mean()

college_tier
1    59.809793
2    59.146863
3    59.284334
Name: AI_tool_usage_frequency, dtype: float64

In [35]:
#Placement status ki unique values
df['placement_status'].unique()

array(['Placed', 'Not Placed'], dtype=object)

In [36]:
#Highest salary package
df["salary_lpa"].max()

np.float64(35.1)

In [37]:
#Lowest salary package
df['salary_lpa'].min()

np.float64(0.0)

In [38]:
#Placed students only
df[df['placement_status'] == 'Placed']['student_id']

0        STU00001
1        STU00002
2        STU00003
3        STU00004
4        STU00005
           ...
24995    STU24996
24996    STU24997
24997    STU24998
24998    STU24999
24999    STU25000
Name: student_id, Length: 24596, dtype: object

In [39]:
df[df['cgpa']>8]

,student_id,age,gender,state,city_tier,college_tier,branch,degree,cgpa,backlog_history,...,salary_lpa,interview_rounds_cleared,offer_count,joining_delay_months,layoffs_risk_score,AI_tool_usage_frequency,prompt_engineering_skill,AI_fear_score,adaptability_score,high_cgpa
4,STU00005,25,Female,West Bengal,3,3,Civil,BE,8.29,0,...,20.57,5,3,5,23,57,67,71,44,1
12,STU00013,20,Male,Gujarat,2,2,AI & DS,MCA,8.31,0,...,21.40,2,1,5,32,35,32,44,51,1
14,STU00015,23,Female,Uttar Pradesh,1,1,Electronics,MCA,9.90,1,...,25.14,3,1,3,19,50,57,14,76,1
18,STU00019,25,Female,Tamil Nadu,1,1,Information Technology,MCA,8.83,2,...,19.83,4,1,4,34,62,55,55,60,1
19,STU00020,23,Female,Uttar Pradesh,1,3,Civil,BE,8.18,0,...,18.11,2,2,3,42,79,57,38,85,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
24988,STU24989,23,Female,Delhi,3,3,AI & DS,BE,8.87,0,...,17.16,3,3,4,29,68,63,46,78,1
24989,STU24990,20,Male,West Bengal,3,2,Electronics,MCA,8.04,0,...,16.62,4,2,2,35,45,57,40,91,1
24992,STU24993,25,Male,Tamil Nadu,3,2,Mechanical,MCA,8.62,0,...,19.97,5,2,0,48,29,56,52,56,1
24994,STU24995,21,Male,West Bengal,2,2,Mechanical,MCA,8.31,0,...,18.60,5,1,2,31,45,48,35,67,1
24995,STU24996,23,Female,Telangana,2,1,Computer Science,MCA,8.42,0,...,26.74,2,2,3,26,55,53,26,53,1

In [40]:
df[df['internships_completed']>0]

,student_id,age,gender,state,city_tier,college_tier,branch,degree,cgpa,backlog_history,...,salary_lpa,interview_rounds_cleared,offer_count,joining_delay_months,layoffs_risk_score,AI_tool_usage_frequency,prompt_engineering_skill,AI_fear_score,adaptability_score,high_cgpa
0,STU00001,22,Male,Karnataka,1,2,Computer Science,MCA,6.71,3,...,17.36,4,1,2,62,55,55,19,81,0
1,STU00002,20,Male,Tamil Nadu,2,3,AI & DS,BTech,6.14,0,...,18.22,3,3,0,55,66,52,54,76,0
2,STU00003,23,Female,Uttar Pradesh,3,2,Computer Science,BTech,7.11,0,...,22.08,1,3,1,79,69,67,49,34,0
3,STU00004,25,Male,Maharashtra,2,3,Civil,BTech,7.41,0,...,20.87,2,1,2,44,44,65,61,46,0
4,STU00005,25,Female,West Bengal,3,3,Civil,BE,8.29,0,...,20.57,5,3,5,23,57,67,71,44,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
24995,STU24996,23,Female,Telangana,2,1,Computer Science,MCA,8.42,0,...,26.74,2,2,3,26,55,53,26,53,1
24996,STU24997,20,Female,Tamil Nadu,2,2,Civil,BTech,7.45,1,...,16.07,1,3,2,27,44,53,81,47,0
24997,STU24998,24,Male,Karnataka,2,3,Mechanical,MCA,7.34,0,...,20.22,4,1,4,17,43,72,24,87,0
24998,STU24999,20,Male,Delhi,2,2,Information Technology,BTech,7.59,1,...,19.79,2,2,3,49,93,53,59,77,0
24999,STU25000,23,Female,Maharashtra,1,2,Civil,BTech,7.67,0,...,16.84,4,1,4,27,81,57,63,55,0

In [41]:
df[df['GitHub_repos']>5]

,student_id,age,gender,state,city_tier,college_tier,branch,degree,cgpa,backlog_history,...,salary_lpa,interview_rounds_cleared,offer_count,joining_delay_months,layoffs_risk_score,AI_tool_usage_frequency,prompt_engineering_skill,AI_fear_score,adaptability_score,high_cgpa
0,STU00001,22,Male,Karnataka,1,2,Computer Science,MCA,6.71,3,...,17.36,4,1,2,62,55,55,19,81,0
1,STU00002,20,Male,Tamil Nadu,2,3,AI & DS,BTech,6.14,0,...,18.22,3,3,0,55,66,52,54,76,0
2,STU00003,23,Female,Uttar Pradesh,3,2,Computer Science,BTech,7.11,0,...,22.08,1,3,1,79,69,67,49,34,0
3,STU00004,25,Male,Maharashtra,2,3,Civil,BTech,7.41,0,...,20.87,2,1,2,44,44,65,61,46,0
4,STU00005,25,Female,West Bengal,3,3,Civil,BE,8.29,0,...,20.57,5,3,5,23,57,67,71,44,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
24995,STU24996,23,Female,Telangana,2,1,Computer Science,MCA,8.42,0,...,26.74,2,2,3,26,55,53,26,53,1
24996,STU24997,20,Female,Tamil Nadu,2,2,Civil,BTech,7.45,1,...,16.07,1,3,2,27,44,53,81,47,0
24997,STU24998,24,Male,Karnataka,2,3,Mechanical,MCA,7.34,0,...,20.22,4,1,4,17,43,72,24,87,0
24998,STU24999,20,Male,Delhi,2,2,Information Technology,BTech,7.59,1,...,19.79,2,2,3,49,93,53,59,77,0
24999,STU25000,23,Female,Maharashtra,1,2,Civil,BTech,7.67,0,...,16.84,4,1,4,27,81,57,63,55,0

In [42]:
df[df['DSA_problems_solved']>200]

,student_id,age,gender,state,city_tier,college_tier,branch,degree,cgpa,backlog_history,...,salary_lpa,interview_rounds_cleared,offer_count,joining_delay_months,layoffs_risk_score,AI_tool_usage_frequency,prompt_engineering_skill,AI_fear_score,adaptability_score,high_cgpa
0,STU00001,22,Male,Karnataka,1,2,Computer Science,MCA,6.71,3,...,17.36,4,1,2,62,55,55,19,81,0
1,STU00002,20,Male,Tamil Nadu,2,3,AI & DS,BTech,6.14,0,...,18.22,3,3,0,55,66,52,54,76,0
2,STU00003,23,Female,Uttar Pradesh,3,2,Computer Science,BTech,7.11,0,...,22.08,1,3,1,79,69,67,49,34,0
3,STU00004,25,Male,Maharashtra,2,3,Civil,BTech,7.41,0,...,20.87,2,1,2,44,44,65,61,46,0
4,STU00005,25,Female,West Bengal,3,3,Civil,BE,8.29,0,...,20.57,5,3,5,23,57,67,71,44,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
24995,STU24996,23,Female,Telangana,2,1,Computer Science,MCA,8.42,0,...,26.74,2,2,3,26,55,53,26,53,1
24996,STU24997,20,Female,Tamil Nadu,2,2,Civil,BTech,7.45,1,...,16.07,1,3,2,27,44,53,81,47,0
24997,STU24998,24,Male,Karnataka,2,3,Mechanical,MCA,7.34,0,...,20.22,4,1,4,17,43,72,24,87,0
24998,STU24999,20,Male,Delhi,2,2,Information Technology,BTech,7.59,1,...,19.79,2,2,3,49,93,53,59,77,0
24999,STU25000,23,Female,Maharashtra,1,2,Civil,BTech,7.67,0,...,16.84,4,1,4,27,81,57,63,55,0

In [43]:
df[df['gender'] == 'Female']

,student_id,age,gender,state,city_tier,college_tier,branch,degree,cgpa,backlog_history,...,salary_lpa,interview_rounds_cleared,offer_count,joining_delay_months,layoffs_risk_score,AI_tool_usage_frequency,prompt_engineering_skill,AI_fear_score,adaptability_score,high_cgpa
2,STU00003,23,Female,Uttar Pradesh,3,2,Computer Science,BTech,7.11,0,...,22.08,1,3,1,79,69,67,49,34,0
4,STU00005,25,Female,West Bengal,3,3,Civil,BE,8.29,0,...,20.57,5,3,5,23,57,67,71,44,1
6,STU00007,20,Female,Karnataka,2,3,Computer Science,BE,7.66,3,...,23.14,2,2,5,30,78,80,52,89,0
7,STU00008,24,Female,Gujarat,2,3,Computer Science,MCA,5.98,0,...,11.43,5,3,0,5,65,40,40,57,0
14,STU00015,23,Female,Uttar Pradesh,1,1,Electronics,MCA,9.90,1,...,25.14,3,1,3,19,50,57,14,76,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
24984,STU24985,25,Female,Maharashtra,3,1,Electronics,MCA,6.86,0,...,18.21,1,1,5,28,25,36,58,78,0
24988,STU24989,23,Female,Delhi,3,3,AI & DS,BE,8.87,0,...,17.16,3,3,4,29,68,63,46,78,1
24995,STU24996,23,Female,Telangana,2,1,Computer Science,MCA,8.42,0,...,26.74,2,2,3,26,55,53,26,53,1
24996,STU24997,20,Female,Tamil Nadu,2,2,Civil,BTech,7.45,1,...,16.07,1,3,2,27,44,53,81,47,0
24999,STU25000,23,Female,Maharashtra,1,2,Civil,BTech,7.67,0,...,16.84,4,1,4,27,81,57,63,55,0

In [44]:
df.sort_values(by='salary_lpa',ascending=False).head(10)

,student_id,age,gender,state,city_tier,college_tier,branch,degree,cgpa,backlog_history,...,salary_lpa,interview_rounds_cleared,offer_count,joining_delay_months,layoffs_risk_score,AI_tool_usage_frequency,prompt_engineering_skill,AI_fear_score,adaptability_score,high_cgpa
5497,STU05498,23,Male,Uttar Pradesh,3,1,Civil,MCA,9.75,0,...,35.10,4,3,2,66,38,75,36,85,1
6014,STU06015,21,Other,Karnataka,1,1,Mechanical,BE,9.29,1,...,34.32,5,3,3,39,50,73,56,77,1
24597,STU24598,25,Female,Tamil Nadu,1,2,Computer Science,BTech,9.33,0,...,34.28,1,1,1,20,75,76,9,39,1
20156,STU20157,22,Male,Telangana,1,1,Information Technology,BE,9.20,1,...,34.03,2,2,5,57,30,84,52,87,1
22792,STU22793,25,Male,Karnataka,3,3,Information Technology,BE,8.18,0,...,33.79,2,1,5,41,100,72,11,73,1
10405,STU10406,20,Male,West Bengal,2,1,Electronics,BTech,9.51,0,...,33.49,1,3,4,58,54,72,21,43,1
415,STU00416,24,Female,Karnataka,3,1,Computer Science,BE,9.81,0,...,33.44,4,1,4,27,59,85,55,78,1
4298,STU04299,20,Female,Maharashtra,1,1,Information Technology,BTech,7.53,1,...,33.20,4,1,0,41,60,100,66,63,0
19953,STU19954,25,Male,West Bengal,2,2,Electronics,MCA,8.24,2,...,33.20,2,1,1,22,69,72,25,52,1
21164,STU21165,22,Male,West Bengal,2,1,Computer Science,MCA,9.09,0,...,32.77,5,3,4,36,96,85,52,40,1

In [45]:
df.sort_values(by='cgpa',ascending=False).head(10)

,student_id,age,gender,state,city_tier,college_tier,branch,degree,cgpa,backlog_history,...,salary_lpa,interview_rounds_cleared,offer_count,joining_delay_months,layoffs_risk_score,AI_tool_usage_frequency,prompt_engineering_skill,AI_fear_score,adaptability_score,high_cgpa
1635,STU01636,22,Female,Gujarat,2,1,AI & DS,MCA,10.0,0,...,25.63,3,3,0,39,53,81,49,84,1
10349,STU10350,20,Female,Karnataka,3,1,AI & DS,BE,10.0,0,...,24.33,2,3,3,16,63,73,35,73,1
19657,STU19658,22,Female,Uttar Pradesh,2,1,Civil,BE,10.0,2,...,21.40,1,3,5,17,48,54,73,71,1
7479,STU07480,23,Female,Gujarat,1,1,Civil,BE,10.0,0,...,26.58,3,2,4,43,94,46,93,65,1
12297,STU12298,22,Female,Tamil Nadu,1,2,Electronics,BTech,10.0,0,...,27.06,2,1,0,17,36,57,74,79,1
5423,STU05424,20,Female,Karnataka,3,2,Electronics,BTech,10.0,0,...,20.76,1,1,2,40,46,72,25,65,1
22419,STU22420,21,Male,Gujarat,1,2,Mechanical,MCA,10.0,0,...,22.95,2,1,5,36,58,70,61,75,1
12716,STU12717,20,Female,West Bengal,1,1,Information Technology,BTech,10.0,1,...,25.39,2,1,2,37,47,56,88,60,1
24556,STU24557,22,Male,Karnataka,1,1,Computer Science,BTech,10.0,0,...,23.11,3,3,2,20,78,46,38,65,1
21777,STU21778,23,Male,Gujarat,1,2,Mechanical,MCA,10.0,0,...,26.65,2,2,3,39,49,79,47,78,1

In [46]:
df.loc[df['attendance_percentage'].idxmin()]

student_id                       STU00631
age                                    22
gender                             Female
state                          Tamil Nadu
city_tier                               3
college_tier                            2
branch                        Electronics
degree                              BTech
cgpa                                 7.54
backlog_history                         0
attendance_percentage                45.0
primary_language                     Java
DSA_problems_solved                   574
GitHub_repos                         27.0
hackathons_participated                 5
development_projects_count             10
AI_ML_projects                          2
internships_completed                   4
resume_score                          100
communication_skills                   92
aptitude_score                         71
mock_interview_score                 83.0
sleep_hours                           4.8
screen_time                           5.1
gaming_hours                          5.0
study_hours_daily                     6.8
stress_level                           32
burnout_score                          36
gym_frequency                           0
family_income_lpa                    8.61
self_learning_hours                   5.2
motivation_level                       58
placement_status                   Placed
company_type                      Startup
work_mode                          Onsite
salary_lpa                          20.58
interview_rounds_cleared                5
offer_count                             2
joining_delay_months                    3
layoffs_risk_score                      4
AI_tool_usage_frequency                84
prompt_engineering_skill               71
AI_fear_score                          33
adaptability_score                     61
high_cgpa                               0
Name: 630, dtype: object

In [47]:
df.groupby('branch')['salary_lpa'].mean()

branch
AI & DS                   18.902166
Civil                     19.093626
Computer Science          18.994851
Electronics               18.937229
Information Technology    19.020826
Mechanical                19.090271
Name: salary_lpa, dtype: float64

In [48]:
df.groupby('gender')['cgpa'].mean()

gender
Female    7.457657
Male      7.461403
Other     7.502923
Name: cgpa, dtype: float64

In [49]:
df.groupby('branch')['resume_score'].mean()

branch
AI & DS                   85.494739
Civil                     85.466153
Computer Science          85.454913
Electronics               85.601776
Information Technology    85.579213
Mechanical                85.642167
Name: resume_score, dtype: float64

In [50]:
df['branch'].value_counts()

branch
Mechanical                4245
Computer Science          4203
AI & DS                   4182
Information Technology    4166
Civil                     4151
Electronics               4053
Name: count, dtype: int64

In [51]:
df.groupby('college_tier')['internships_completed'].mean()

college_tier
1    3.005090
2    2.873041
3    2.830381
Name: internships_completed, dtype: float64

In [52]:
placed = df[df['placement_status']=='Placed']
placed['state'].value_counts().idxmax()

'West Bengal'

In [53]:
df[['GitHub_repos','salary_lpa']].sort_values('salary_lpa',ascending=False)

       GitHub_repos  salary_lpa
5497           55.0       35.10
6014           32.0       34.32
24597          44.0       34.28
20156          46.0       34.03
22792          56.0       33.79
...             ...         ...
14084           7.0        0.00
14095          27.0        0.00
20079           7.0        0.00
14129          11.0        0.00
18533           9.0        0.00

[25000 rows x 2 columns]

In [54]:
df.groupby('GitHub_repos')['salary_lpa'].mean()

GitHub_repos
0.0     15.012947
1.0     15.554753
2.0     15.523565
3.0     15.870000
4.0     16.114135
5.0     16.069890
6.0     16.525392
7.0     16.155578
8.0     16.695299
9.0     17.087654
10.0    17.253760
11.0    17.284393
12.0    17.598924
13.0    17.721069
14.0    17.923535
15.0    18.129344
16.0    18.322964
17.0    18.543447
18.0    18.801590
19.0    18.980563
20.0    19.178500
21.0    19.592237
22.0    19.850031
23.0    19.840046
24.0    20.187996
25.0    20.418814
26.0    20.634972
27.0    20.554486
28.0    20.784409
29.0    21.292783
30.0    21.641845
31.0    21.503160
32.0    21.913791
33.0    22.231861
34.0    22.562248
35.0    22.685837
36.0    22.614837
37.0    23.360643
38.0    22.902361
39.0    23.727568
40.0    24.425000
41.0    23.992903
42.0    24.022982
43.0    24.411702
44.0    25.283784
45.0    24.618636
46.0    26.983750
47.0    25.512500
48.0    24.916667
49.0    28.010000
50.0    26.310000
51.0    24.596667
52.0    25.936667
53.0    29.377500
54.0    26.270000
55.0    30.780000
56.0    33.790000
60.0    26.180000
Name: salary_lpa, dtype: float64

In [55]:
df[['GitHub_repos','salary_lpa']].corr()

              GitHub_repos  salary_lpa
GitHub_repos      1.000000    0.467154
salary_lpa        0.467154    1.000000

Yes, there is a moderate positive correlation (0.47) between GitHub repositories and salary. Students with more GitHub repositories tend to earn higher salaries, but the relationship is not very strong.

In [56]:
df[['cgpa', 'salary_lpa']].corr()

                cgpa  salary_lpa
cgpa        1.000000    0.494012
salary_lpa  0.494012    1.000000

In [61]:
df[['internships_completed','salary_lpa']].corr()

                       internships_completed  salary_lpa
internships_completed                1.00000     0.54165
salary_lpa                           0.54165     1.00000